ethereum/eth-tester

eth_tester/backends/pyevm/main.py
setup.py
tox.ini

1) The import path of py-evm's `MainnetTesterChain` is wrong.
2) The db generated by `get_db_backend()` is `DB` type, not a `ChainDB`, which has method like `get_state_db()`
1) Correct it to the path of the `MainnetTesterChain` in the latest commit in py-evm master branch.
2) Create a `BaseChainDB` instance from the result of `get_db_backend()`
After fixing these, we can use PyEVMBackend as the backend of `EthereumTester` by
```python
from eth_tester import EthereumTester
from eth_tester.backends.pyevm import PyEVMBackend
t = EthereumTester(PyEVMBackend())
```

Fix `setup_tester_chain()`

---

.gitignore
eth_tester/utils/backend_testing.py
eth_tester/utils/filters.py
tests/core/filter-utils/test_filter_helpers.py

Filters were overly aggressive. A log with topics `[A, B]` was not matching filter topics `[A]`.
See https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter
eg~
> A transaction with a log with topics [A, B]
will be matched by the following topic filters:
> - `[A]` "A in first position (and anything after)"
> - ...
- Fixed a couple of incorrect tests. Added several new ones.
- Only preemptively reject log topics if they are shorter than the filter topics (previously any mismatch)

 Match filter prefix against longer topic list

---

requirements-dev.txt

`ethereum-abi-utils` was a dev requirement and wasn't updated to the new library name `eth-abi`
Updated it in `requirements-dev.txt`

Fix dev dependency that wasn't renamed

---

eth_tester/backends/mock/factory.py
eth_tester/validation/inbound.py
tests/core/validation/test_inbound_validation.py

The `nonce` field was not one of the allowed fields for inbound transactions.
Adjusted inbound validators to accept it.

Allow nonce field for inbound transactions

---

setup.py

All versions were either `==` or `>=` which was either too precise (such as with cytoolz) or imprecise allowing breaking changes to be installed since `>=` will upgrade to anything.
Put explicit caps on what versions can be installed to keep us within a single major version for all dependencies.

more explicit version range specifiers

---

.travis.yml

Py-EVM backend was only tested against python3.5
Added 3.6 to the test matrix

Test Py-EVM backend against python3.6

---

eth_tester/normalization/inbound.py
eth_tester/utils/backend_testing.py

eth-tester crashes when creating a filter with a list of topics that includes `None`
It was discovered by trying to swap in eth-tester for eth-testrpc in the web3 test suite: https://github.com/ethereum/web3.py/issues/505
Don't `decode_hex()` on `None` values.

normalize list of topics with None

---

eth_tester/backends/pyevm/main.py
setup.py
tox.ini

Due to the modification of VM class in PyEVM, the structure has changed and some attribute is no longer under `VM`. So any access to those attributes like `PyEVMBackend.get_nonce()` doing will fail.
Change some usage of `vm.xxx` to `vm.state.xxx`

Fix pyevm backend 

---

eth_tester/main.py

Calling time travel to a time you're already at disrupted the space-time continuum. It should stay undisturbed.
This caused errors in web3 testing.
If the desired time is exactly the current time, then no further action takes place and no error is raised.

Allow time-travel in place

---

.gitignore
eth_tester/backends/pyevm/main.py
eth_tester/utils/backend_testing.py

It is surprising to require a `gas` field when estimating the amount of gas required.
- Modify the test to try a transaction without gas specified
- (in py-evm) Estimate gas by supplying all available gas in the block, and ignore the specified gas
- Run estimate against pending block instead of latest block, to make sure plenty of gas left in block
- Add a bit of wiggle-room to the estimate (it was too restrictive and causing OOG errors on some web3 tests)
- Enforce a minimum estimate, some scenarios were returning 0 gas used (I guess a failure?)

make `gas` field optional when estimating gas

---

eth_tester/backends/pyethereum/v20/main.py
eth_tester/backends/pyevm/main.py
eth_tester/utils/backend_testing.py
eth_tester/utils/formatting.py

eth-tester was raising a py-evm exception that web3 didn't recognize: `BlockNotFound`
catch and re-raise the exception as an eth-tester standard `BlockNotFound`

Catch py-evm BlockNotFound, reraise as eth-tester BlockNotFound

---

.travis.yml
eth_tester/main.py
eth_tester/utils/backend_testing.py

The corresponding method in `eth_tester` of RPC `eth_getLogs` is not implemented, and it is needed in https://github.com/ethereum/py-evm/pull/265
Implement `get_logs_directly`, which accepts `filter_params` and output the logs directly, without installing filters.

Add `get_logs` for RPC `eth_getLogs`

---

eth_tester/backends/pyevm/main.py

`eth_call` without gas was rejected
Default the gas to all gas available in the block.

[py-evm] Call with all available gas, if gas is not set

---

eth_tester/backends/pyevm/main.py
eth_tester/backends/pyevm/serializers.py
setup.py
tox.ini

py-evm's API changed a lot between alpha 8 and 9, breaking eth-tester.
So much `pdbpp`.
Things I found:
- The public API to apply a transaction to the pending block seems to have gone away! I had to manually set the chain header.
- `vm.execute_transaction()` => `state.execute_transaction()`
- `block.receipts` went away

Now compatible with py-evm alpha 9

---

eth_tester/backends/pyevm/main.py
setup.py

The interface of Py-EVM is changed, so it's not compatible with the latest Py-EVM.
1. Update `eth_tester.backends.pyevm.main._execute_and_revert_transaction`.
2. Update Py-EVM version.
3. In Py-EVM, `BaseChainDB.set_as_canonical_chain_head` was renamed to `BaseChainDB._set_as_canonical_chain_head`, so I also have to change where `eth-tester` calls this function, but it may look not good to call a protected function of py-evm. Do we need to open an issue for that?

Upgrade to Py-EVM 0.2.0a10 compatible 

---

setup.py
tox.ini

https://github.com/ethereum/eth-abi/issues/25 there should be an eth-tester release that supports eth-utils v1.
bump version, everything looks compatible.

upgrade to eth-utils v1, drop unused tox envs

---

eth_tester/backends/pyethereum/v20/main.py
eth_tester/backends/pyevm/main.py
eth_tester/utils/backend_testing.py
tests/backends/test_pyethereum16.py

In order to implement comprehensive tests for https://github.com/ethereum/web3.py/pull/552 we needed to add functionality to `eth_tester` that allowed one to query past chain state using the `call` method.
A block_number parameter was passed to the `_execute_and_revert_transaction` function and then also passed through to `_get_normalized_and_signed_evm_transaction` function in order to make sure the nonces matched so that the call method's "transaction" could be executed and then reverted.

Allow call method to query past state

---

eth_tester/main.py
eth_tester/utils/backend_testing.py
eth_tester/utils/transactions.py
tests/core/test_transaction_utils.py

Eth tester does not handle pending transactions correctly when disabling auto mining transactions:
Sending a transaction with the same nonce causes an invalid nonce error when auto mining transactions are disabled.
The issue is that `send_transaction` and `send_raw_transaction` immediately execute on the vm's state and thereby increment the valid nonce.
Implement a transaction pool at the `eth-tester` level so that transactions are only executed when auto mining is enabled again.
Fixes #59

Handle pending transactions

---

.gitignore
Makefile
eth_tester/main.py
eth_tester/utils/backend_testing.py
tox.ini

If auto-mine was off, then manually running `mine_block()` was not mining the pending transactions.
- Explicitly check for pending transactions on a `mine_block()` call, and add them to the block
- Plus some refactoring to reduce code duplication. 
- Some config cleanup

Manually mine pending transactions

---

setup.py

py-evm API is still in heavy flux. A new breaking change is about to come through (see https://github.com/ethereum/py-evm/pull/424 )
Pin py-evm to exact version. Upgrade manually and re-run tests at every upgrade.

pin py-evm to exact version, plus comment

---

eth_tester/backends/base.py
eth_tester/backends/pyethereum/v16/main.py
eth_tester/backends/pyethereum/v20/main.py

The base backend class didn't use the utilities provided by the `abc` module for abstract base classes.
Added the metaclass and the `abstractmethod` decorator to the base backend class.

use abc for backend base class

---

eth_tester/utils/backend_testing.py
requirements-dev.txt
tests/backends/test_pyethereum16.py
tests/backends/test_pyethereum21.py
tests/core/test_mock_backend.py

I am a little to in love with property based testing and originally wrote some fuzz testers for the backends.  They mostly aren't used and are not really useful.
Removed them.

remove fuzz tests

---

README.md

PyEthereum16Backend import example is outdated.
updated it.

update PyEthereum16Backend import example

---

eth_tester/backends/pyevm/main.py
requirements-dev.txt
setup.py
tox.ini

Upstream changes to py-evm needed to be accounted for.

Update to latest py-evm

---

eth_tester/backends/pyevm/main.py
eth_tester/utils/backend_testing.py
setup.py
tests/backends/test_pyevm.py

depends on: https://github.com/ethereum/py-evm/pull/432
eth-tester implemented `estimate_gas` before py-evm.
This change delegates the py-evm backends `estimate_gas` to py-evm.

Move estimate_gas to vm level in py-evm backend

---

eth_tester/backends/pyevm/main.py
eth_tester/utils/backend_testing.py

Its a required field for transaction objects
Gas estimation fails if a gas parameter is not supplied.
Insert a value for gas when creating the evm transaction.

Insert gas value when creating tx for gas estimation

---

README.md

The project description was not rendering on pypi.
Hunting down invalid rst formatting with a lot of `restview --long --pypi`, and tweaking the markdown so it can be converted correctly.
Also a couple bonus link target fixups.
_Do we even need all these manual targets? Targets are automatically generated at the headers, so the value seems minimal_

Tweak readme so rst output for pypi is valid

---

eth_tester/backends/mock/serializers.py
eth_tester/backends/pyethereum/serializers.py
eth_tester/backends/pyevm/main.py
eth_tester/backends/pyevm/serializers.py
eth_tester/main.py
eth_tester/normalization/outbound.py
eth_tester/utils/backend_testing.py
eth_tester/validation/outbound.py
tests/backends/test_pyethereum16.py
tests/core/test_mock_backend.py
tests/core/validation/test_outbound_validation.py

Receipts in `eth-tester` don't include `status` field. In Raiden, it prevents us from using `eth-tester` backend for our tests/CI.
Status field was added for transactions  that occur after `FORK_BYZANTIUM`. I've used some ideas discussed in #93

Add `status` field to Byzantium tx receipts

---

.circleci/config.yml

Fixes #103 
Otherwise, we get a libcrypto-1.0.0 missing error when trying to install
scrypt for pyethereum21.
Tweak the CircleCI environment to make sure the right libraries are available

Force py36 pyethereum21 test to debian 8: Jessie

---

.circleci/config.yml
eth_tester/backends/pyevm/main.py
setup.py

Fix #104 
The tester chain was not ignoring proof of work by default in py-evm alpha 26. Created a subclass that correctly ignores PoW.
Plus bonus upgrade of eth-hash.

Pyevm upgrade a26

---

eth_tester/validation/outbound.py

V value validation in signature supported only 0, 1, 27 and 28 values. When using latest Web3.py raw transactions have v set to 37/38 so validation fails.
Adding 37 and 38 as valid values resolves this issue.

Update v signature validation to support 37 and 38

---

eth_tester/main.py
eth_tester/utils/backend_testing.py

Issue #112 
`Filter::add()` wont process an item if log with a same txhash already exists.

Fix duplicate log when using multiple filters

---

eth_tester/backends/pyethereum/v16/main.py
eth_tester/backends/pyethereum/v20/main.py
eth_tester/backends/pyevm/main.py
eth_tester/exceptions.py

The `pkg_resources.DistributionNotFound` class doesn't actually accept custom error messages.
```
>>> import pkg_resources
>>> raise pkg_resources.DistributionNotFound("abc")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
pkg_resources.DistributionNotFound: <exception str() failed>
```
as can be seen, `abc` is thrown away. 
https://github.com/pypa/setuptools/blob/cca86c7f1d4040834c3265ccecdd9e21b4036df5/pkg_resources/__init__.py#L293
Create a new Exception type

use custom BackendDistributionNotFound class

---

.circleci/config.yml
README.md
eth_tester/backends/base.py
eth_tester/backends/mock/main.py
eth_tester/backends/pyethereum/v16/main.py
eth_tester/backends/pyethereum/v20/main.py
eth_tester/backends/pyevm/main.py
eth_tester/main.py
eth_tester/utils/backend_testing.py
setup.py
tox.ini

- switch from `Chain` to `MiningChain` which means we have to stop using the prebuilt tester chain (although py-evm should probably switch to using a `MiningChain`)
- change module name from `evm` to `eth`
- change a keyword argument from header to `at_header`
- drop an unused `configure_forks` feature that was broken anyway, last I checked.

Compatibility with py-evm v0.2.0-alpha.28

---

eth_tester/normalization/inbound.py
eth_tester/utils/filters.py
eth_tester/validation/inbound.py
tests/core/filter-utils/test_filter_helpers.py
tests/core/validation/test_inbound_validation.py

Validators disallow topics lists such as:
[TOPICA, [TOPICB, TOPICC], TOPICD]
EDIT: fixes #119
The topic validators were extended to check the validity of single items along with flat topic arrays.

Fix topic_list parameter implementation (matching and validation) to align with JSON-RPC spec

---

eth_tester/main.py
eth_tester/utils/backend_testing.py

filter didn't include logs  from block with `blockNumber=to_block`, when `to_block` was passed as a parameter to `create_log_filter`.
Increased `upper_bound` by 1 when `to_block` is passed. 
https://github.com/ethereum/eth-tester/blob/a0ac1bc9dd5c467e41e6d841a374b28b72fa8701/eth_tester/main.py#L611

fixed filters to work correctly when to_block points to latest block

---

setup.py

A project that used `web3.py` and `eth-tester` would give the following error on installing. 
`py-evm 0.2.0a30 has requirement web3==4.4.1, but you'll have web3 4.6.0 which is incompatible`
A fix for this was submitted in https://github.com/ethereum/py-evm/pull/1193 and was released in 
`0.2.0a32`. Updated `py-evm` version in `eth-tester` to see the fix reflected.

updated py-evm version to 0.2.0a32

---

setup.py

`eth-tester` would give the following error:
```
In [1]: from eth_tester import EthereumTester
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-72c9d4f19b88> in <module>()
----> 1 from eth_tester import EthereumTester
~/Projects/eth-tester/eth_tester/__init__.py in <module>()
2 import sys
3
----> 4 from .main import (  # noqa: F401
5     EthereumTester,
6 )
~/Projects/eth-tester/eth_tester/main.py in <module>()
29 )
30
---> 31 from eth_tester.backends import (
32     get_chain_backend,
33 )
~/Projects/eth-tester/eth_tester/backends/__init__.py in <module>()
10     MockBackend,
11 )
---> 12 from .pyevm import (  # noqa: F401
13     PyEVMBackend,
14     is_pyevm_available, …
```

Made eth-abi a primary dependency

---

eth_tester/backends/pyevm/main.py
tests/backends/test_pyevm.py

When supplying an invalid from address, one would receive a KeyError.
Throws a more useful exception.

Add exception message to from

---

eth_tester/utils/backend_testing.py
setup.py

This change is needed for `py-ethpm` and `pytest-ethereum` to update to `web3` v5.
🐇

Update eth-abi dependency to v2

---

eth_tester/backends/pyevm/main.py
setup.py

As of recent PR <https://github.com/ethereum/py-evm/pull/1662> - Installing `py-evm` version `0.2.0-alpha.38` results in a failing test suite that produces the following Exception:
`E   ModuleNotFoundError: No module named 'eth.utils'`
- Pinned `py-evm` version to `0.2.0a38` in `setup.py`
- Updated one import `eth.utils.SpoofTransaction` -> `eth.vm.SpoofTransaction`

Pin py-evm==0.2.0a38 and reflect SpoofTransaction import path change

---

eth_tester/backends/pyevm/main.py
eth_tester/main.py

eth-tester was pinned to use the Byzantium vm rules, which are not compatible with newer versions of solidity. Updated to use the Constantinople vm rules by default. 
See [this issue](https://github.com/ethereum/py-evm/issues/1748)

Update default vm rules

---

CHANGELOG
eth_tester/backends/pyevm/main.py

eth-tester was defaulting to Constantinople (not even St Petersburg!)
Default to Istanbul

Default py-evm backend VM to Istanbul

---

eth_tester/backends/pyevm/main.py
setup.py

Incompatibility with py-evm by dint of the backend.  Here's an example traceback: https://gist.github.com/jMyles/4a32dff65edf5b5b22ecbe4e24c24d70
The change to py-evm which caused this API modification is here: https://github.com/ethereum/py-evm/commit/bfdcf12fce8f2827ed802ec73bdb351ac99a5f8d
By passing the full header instead of just the hash.

py-evm expects the block header, not the hash, as of v0.3.0-alpha.11.

---

eth_tester/backends/pyevm/main.py
setup.py

Istanbul fork was still used.
Update to Muir Glacier. As nothing but the ice age delay changed this shouldn't cause trouble.

Default py-evm backend VM to Muir Glacier

---

README.md

#154 -- docs say that time traveling immediately results in a new block being mined. It does not.
Updated the docs. (Later, it's the functionality that should change)

docs: time-travel note about needing to mine

---

CHANGELOG
setup.py

Permit older eth-keys as we have other libraries that still constrain to
<v0.3 for now.
eth-keys was constrained to `0.2.*`, and we want `0.3.*` to get rid of deprecation warnings.
Update the setup file.

Upgrade eth-keys for updated eth-typing usage

---

CHANGELOG
setup.py

Current impetus is eth-keys flexibility. Hooray for having py-evm not break any APIs! :)

Upgrade py evm

---

.github/PULL_REQUEST_TEMPLATE.md

Referenced the CHANGELOG to make versioning decisions for web3.py, but it doesn't reflect all changes.
At least nudge contributors to update the changelog each PR.

Update PR template to nudge changelog addition

---

CHANGELOG
eth_tester/backends/base.py
eth_tester/backends/pyevm/main.py
eth_tester/main.py
eth_tester/utils/backend_testing.py

Re: https://github.com/ethereum/web3.py/pull/1639, py-evm supports gas estimation with block identifiers, but eth-tester didn't yet pass those values through.
`estimate_gas` now accepts and processes a `block_number`.
Feedback appreciated @carver (and anyone else interested); I processed the minimum surface area of this package required to get this far and get passing tests on the [Web3 side](https://github.com/ethereum/web3.py/pull/1639).

support gas estimates with block identifier

---

CHANGELOG
eth_tester/backends/pyevm/main.py
tests/backends/test_pyevm.py

The `py-evm` backend was hardcoded to use the latest VM ruleset. This makes it difficult to experiment with or test future forks using this library.
A custom VM class can now be passed to the `py-evm` backend constructor.

Allow `py-evm` backend to use a custom VM

---

CHANGELOG
eth_tester/backends/pyevm/main.py
eth_tester/utils/backend_testing.py
tests/backends/test_pyevm.py

Make gas limit constant

---

.circleci/config.yml
CHANGELOG
setup.py
tox.ini

Wanted to support latest rlp. See ethereum/trinity#2004
- Allow latest pyrlp version
- Drop all tox tests for pypy (not compatible with pyrlp)
- Add tests for py3.8

Upgrade rlp

---

CHANGELOG
setup.py

Using old py-evm
Upgrade it to v0.3.0-alpha.19

Upgrade py-evm to v0.3.0-alpha.19

---

setup.py

The current RLP dependency has a hard bound on `2.0.0a1`. Trinity, Py-EVM and friends need to migrate to `2.0.0a2` so we need to update the dependency. 
Changed it to `"rlp>=1,<3"` which is  inline with what [`eth-enr` does](https://github.com/ethereum/eth-enr/blob/master/setup.py#L64) and causes less cascading releases whenever we cut a new alpha release of RLP.

Relax upper bound of RLP dependency

---

setup.py

Updated `py-evm` version is needed for compatibility with `rlp==2.0.0`
Pinned new `py-evm` version in `setup.py`

Update pinned py-evm version

---

CHANGELOG
eth_tester/backends/pyevm/main.py
eth_tester/utils/backend_testing.py
setup.py
tests/backends/test_pyevm.py

Using a pre-Berlin evm.
Update py-evm. Set default VM to Berlin. Resolve a couple changed APIs.

Update py-evm for Berlin support

---

.circleci/config.yml
.gitignore
CHANGELOG
setup.py
tox.ini

A py-evm update is required to bring eth-tester and web3.py (https://github.com/ethereum/web3.py/issues/1769) into the 3.9 age.

add python 3.9 support

---

CHANGELOG
README.md

README had a confusing sentence
Use the word that was probably meant to be used in the readme.
)

fix: use correct word

---

CHANGELOG
README.md
eth_tester/backends/pyevm/main.py
setup.py
tests/backends/test_pyevm.py

I need to be able to control which accounts get funded. The way I have done this with other providers is via mnemonic. I was hoping we can add mnemonic support here as well?  Or at least, a way to set the private keys? I am able to set genesis data for funding accounts, but I can't actually make eth-tester use those accounts.
Added `mnemonic` parameter and handle it by using tooling from `eth-account` to generate accounts that way instead of using the default.

feat: support mnemonic when generating genesis accounts

---

CHANGELOG
README.md
eth_tester/backends/pyevm/main.py
tests/backends/test_pyevm.py

The README recommends using protected methods. It is difficult to know if this method is considered public or an implementation detail. I would like to be able to call these methods and not worry that they may break at some point.
I made "public" classmethods that passthrough to the original static methods. This way, users who may be calling the protected methods won't have their stuff break.

chore: create public versions of methods

---

CHANGELOG
README.md

- There was an older Travis CI link in the readme for the CI build status
- Replaced the Travis CI link with the link to Circle CI

Update README.md with correct CI build status path

---

CHANGELOG
eth_tester/backends/pyevm/serializers.py
tests/backends/test_pyevm.py

Closes issue #216 - Base fee per gas was being added for all blocks, even those prior to London, which was causing an AttributeError.
If the block is London or above, add `base_fee_per_gas` to the block attributes. Otherwise, leave it off.

Don't add base_fee to block serializer until London

---

.circleci/config.yml
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG
Makefile
newsfragments/218.bugfix.rst
newsfragments/224.bugfix.rst
newsfragments/README.md
newsfragments/validate_files.py
pyproject.toml
setup.py
tox.ini

We kept getting merge conflicts with the CHANGELOG. This PR should prevent that. 
Configured towncrier, and set up CI to make sure the newsfragment file formats are correct.

Add towncrier

---

eth_tester/normalization/outbound.py
eth_tester/validation/outbound.py
newsfragments/227.bugfix.rst
tests/backends/test_pyevm.py

- We had removed ``base_fee_per_gas`` serialization from pre-London blocks but we were still validating all blocks equally. This would break pre-London blocks on a simple `get_block()` call.
- Set ``base_fee_per_gas`` value to ``None`` during validation if the param is missing (pre-London blocks). Pop this value back out during block normalization. This returns a block without a ``base_fee_per_gas`` for pre-London blocks which seems to be the default behavior in other clients as well.

Support for pre-London blocks missing a base fee during validation

---

.circleci/config.yml
newsfragments/231.feature.rst
newsfragments/231.removal.rst
setup.py
tox.ini

Adds Python 3.10 support, drops python 3.6 support. This is needed for our other dependency upgrades.

Drop Python 3.6 support, add Python 3.10 support

---

newsfragments/230.misc.rst
setup.py

Updated dependency requirements for py-evm, eth-abi, eth-account, eth-keys, eth-utils, and pyrlp.

Update dependency requirements for py-evm, eth-abi, eth-account, eth-keys, eth-utils, pyrlp

---

newsfragments/232.bugfix.rst
setup.py

See https://github.com/ethereum/py-evm/pull/2050. I did a premature upgrading of dependencies with breaking changes. Once we're ready to cut a new web3.py v6 branch, we can pull in the breaking upstream dependencies.
Pulled in the needed non-breaking changes, and left the breaking changes until we're ready to cut a new web3.py v6.

Downgrade upstream dependency requirements

---

Makefile
newsfragments/230.misc.rst
setup.py

Need to upgrade the dependencies and issue a sem-versioned breaking release
Cherry-picked the correct commit, upgraded py-evm since that has the right sem version now, and upgraded towncrier. I could totes pull out the towncrier version into another PR if anyone feels strongly. I also made sure all these dependencies install in web3 v6.

Breaking Dependency Changes

---

eth_tester/tools/gas_burner_contract.py
eth_tester/utils/emitter_contract.py
eth_tester/utils/math_contract.py
eth_tester/utils/throws_contract.py
newsfragments/242.feature.rst

We were still calling the deprecated method eth_abi.encode_abi.
Changed all calls to the new eth_abi.encode.

update all references to deprecated eth_abi.encode_abi to eth_abi.encode

---

newsfragments/250.misc.rst
setup.py
tox.ini

In order to get dependencies to resolve in web3.py for Python 3.11 support, we had to upgrade the eth-abi dependency via eth-account.
Removed the upper pin on eth-account to support the latest release.

upgrade eth-account dependency requirement

---

newsfragments/251.misc.rst
setup.py

web3.py isn't able to resolve dependencies for Python 3.11 support. Had to remove the upper pin of `eth-bloom` in `py-evm` and then pull that in here. 
Bumped py-evm to a version that might resolve for web3.py

Bump py-evm

---

eth_tester/backends/mock/factory.py
eth_tester/backends/mock/serializers.py
eth_tester/backends/pyevm/main.py
eth_tester/backends/pyevm/serializers.py
eth_tester/constants.py
eth_tester/normalization/outbound.py
eth_tester/utils/backend_testing.py
eth_tester/validation/common.py
eth_tester/validation/inbound.py
eth_tester/validation/outbound.py
newsfragments/257.feature.rst
setup.py
tests/backends/test_pyevm.py
tests/core/validation/test_inbound_validation.py
tests/core/validation/test_outbound_validation.py

- Needs Shanghai support, mostly in the form of supporting withdrawals.
Note: This PR revealed a bug in the link between eth-tester and py-evm. This PR will fail until [this fix](https://github.com/ethereum/py-evm/pull/2105) is merged and release.
- Added `withdrawals` and `withdrawals_root` fields where appropriate
- Added a way to `apply_withdrawal()`, passing in a dict with appropriate values via a method on `PyEVMBackend` since withdrawals are not done via an API call on EL, but rather through configs on the CL client.
- Added some testing around outbound blocks with withdrawals.
- Added validation for "inbound" withdrawals dict object for the `apply_withdrawal()` method.
```
/\ /\
( oo)
=======~~~
/\    /\
```

Shanghai support, pending `py-evm` release

---

eth_tester/backends/pyevm/main.py
eth_tester/main.py
eth_tester/normalization/base.py
eth_tester/normalization/common.py
eth_tester/normalization/default.py
eth_tester/validation/base.py
eth_tester/validation/default.py
eth_tester/validation/inbound.py
newsfragments/264.feature.rst
tests/backends/test_pyevm.py
tests/core/normalization/test_default_outbound_normalization.py
tests/core/validation/test_inbound_validation.py

closes #263 
- Implement `get_storage_at()` with validation and normalization for inbound `storage_slot` value and outbound `storage` value
- Add tests
- Tested against a local `web3.py` branch for compatibility, that PR will be coming after this is merged and released.

Implement `get_storage_at()`

---

newsfragments/268.internal.rst
setup.py

py-evm had some changes that haven't been pulled into eth-tester just yet. 
Bumped the dependency.

Bump py-evm version requirement

---

README.md
eth_tester/backends/mock/main.py
eth_tester/backends/pyevm/main.py
eth_tester/main.py
eth_tester/utils/backend_testing.py
newsfragments/258.feature.rst

Closes #258
Add RPC endpoint to backends for eth_feeHistory

fee history endpoint
