ethereum/eth-tester

README.md
eth_tester/main.py

start writing documentation

---

eth_tester/validation/inbound.py
setup.py

dependency for recent rlp version

rlp >= 0.5.1

---

.bumpversion.cfg
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
eth_tester/__init__.py
eth_tester/backends/__init__.py
requirements-dev.txt
setup.py

* github migration
* python2 deprecation
* bumpversion for releases.

github migration, python2, bumpversion

---

.travis.yml
setup.py
tox.ini

Not testing against 3.6
Added 3.6 env to core environment

expand tests to python3.6

---

eth_tester/backends/mock/factory.py
eth_tester/backends/pyethereum/v16/main.py
eth_tester/backends/pyethereum/v20/main.py
eth_tester/backends/pyevm/main.py
eth_tester/backends/pyevm/serializers.py
eth_tester/normalization/inbound.py
eth_tester/utils/encoding.py
eth_tester/utils/secp256k1.py
requirements-dev.txt
setup.py

left_pad was removed from eth-utils.
replaced left_pad with rjust built-in method.

Replace left_pad with rjust

---

README.md

broken internal link in readme
updated link

fix broken internal link in README

---

eth_tester/backends/pyevm/main.py
setup.py

More upstream fixes and changes in Py-EVM
Bumped the version.

Bump Py-EVM version

---

README.md

#123 did not include an update to the Readme.
Provided walkthough and code samples explaining how to build and use custom genesis state and parameters.
Fixes #132

Update Readme with genesis overriding examples

---

setup.py

Update `eth-abi` and `eth-utils` dependencies
🐼

Update eth-abi and eth-utils

---

setup.py

Fixes #151 
Updated `py-evm` and `pytest` dependencies.

Update py-evm version to latest alpha

---

eth_tester/backends/pyevm/main.py
setup.py

Fixed issues in #158.
Fixes #157 
Did as @carver said.

Upgrade to py-evm v0.2.0-alpha.43

---

.bumpversion.cfg
setup.py

I screwed up #161 and merged to this branch used in #158 
Completely merge these branches

Pyevm upgrade

---

setup.py

Want the latest py-evm
Just bump it and see what happens

Upgrade to py-evm v0.3.0a1

---

CHANGELOG
eth_tester/backends/pyevm/main.py
setup.py

Closes #165 
- Update `VMState.execute_transaction` -> `VMState.apply_transaction`
- Add genesis parent hash when setting the canonical head

Upgrade py-evm

---

CHANGELOG
setup.py

Want the latest py-evm goodies, especially to resolve the bug reported here:
https://github.com/ethereum/vyper/pull/1657#discussion_r339643967
and merged here: https://github.com/ethereum/py-evm/issues/1865
Update to latest py-evm and see what breaks

Upgrade py-evm to v0.3.0-alpha.8

---

README.md
eth_tester/backends/mock/factory.py
eth_tester/backends/mock/main.py
eth_tester/backends/pyevm/main.py
eth_tester/utils/backend_testing.py

#154 - if I'm not misunderstanding, all that needs to happen is to automine a single block with every `time_travel`. 
Added `mine_blocks` functionality to `time_travel`

Mine blocks on time travel

---

README.md
newsfragments/226.doc.rst

README had outdated release instructions. 
Fixed them!

Update README with release instructions

---

.circleci/config.yml
CHANGELOG
README.md
eth_tester/backends/pyevm/serializers.py
eth_tester/normalization/common.py
tests/backends/test_pyevm.py

copy of PR #254 but `gh` had some strange behavior when squashing; merging here with cherry-picked commit
... also adding in recent changes to the repo template that fix circleci issues with `virtualenv`

✏️ Fix typos

---

eth_tester/normalization/outbound.py
eth_tester/validation/inbound.py
newsfragments/261.bugfix.rst
pytest.ini
setup.py
tests/__init__.py
tests/core/normalization/test_outbound_normalization.py
tests/core/validation/test_outbound_validation.py
tests/utils.py

Don't return a contract address if the contract deployment transaction failed. This can only lead to issues.

Better UX for contract deployment

---

eth_tester/normalization/inbound.py
eth_tester/utils/backend_testing.py
eth_tester/validation/inbound.py
newsfragments/185.feature.rst
tests/core/validation/test_inbound_validation.py

Add ability to filter logs using bytes for topics
